plugins: ['jekyll/scholar']
markdown: kramdown

style: davewhipp

scholar:
  bibliography_template: bib
  sort_by: year,month
  order: descending
  style: _bibliography/apa-cv
  replace_strings: false
  bibtex_filters:
  - latex
  - markdown

kramdown:
  parse_block_html: true